# Generated by Django 4.2.6 on 2023-10-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flights',
            new_name='Flight',
        ),
    ]
